# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0b\x63om.vectara\"T\n\x15\x44\x65leteDocumentRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x03\x12\x11\n\tcorpus_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x64ocument_id\x18\x03 \x01(\t\"\x18\n\x16\x44\x65leteDocumentResponse\"=\n\x0cStorageQuota\x12\x11\n\tnum_chars\x18\x01 \x01(\x03\x12\x1a\n\x12num_metadata_chars\x18\x02 \x01(\x03\x42<\n\x0b\x63om.vectaraB\x0c\x43ommonProtosZ\x1fvectara.com/public/proto/commonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013com.vectaraB\014CommonProtosZ\037vectara.com/public/proto/common'
  _DELETEDOCUMENTREQUEST._serialized_start=29
  _DELETEDOCUMENTREQUEST._serialized_end=113
  _DELETEDOCUMENTRESPONSE._serialized_start=115
  _DELETEDOCUMENTRESPONSE._serialized_end=139
  _STORAGEQUOTA._serialized_start=141
  _STORAGEQUOTA._serialized_end=202
# @@protoc_insertion_point(module_scope)
