version: '3'

services:

  django:
    restart: always
    build: .
    image: django
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file: .env_local
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_CONFIGURATION: DEV
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      DEMO_USERNAME: Demo
    depends_on:
      - redis
      - worker
  worker:
    build: .
    env_file: .env_local
    image: celery
    volumes:
      - .:/usr/src/app
    command: celery -A poma worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
  monitor:
    image: flower
    build: .
    env_file: .env_local
    ports:
      - "5555:5555"
    command: [ 'celery', '-A', 'poma', 'flower' ]
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
