# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import custom_dim_pb2 as custom__dim__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eindexing.proto\x12\x14\x63om.vectara.indexing\x1a\x10\x63ustom_dim.proto\"\xb5\x01\n\x07Section\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x15\n\rmetadata_json\x18\x04 \x01(\t\x12:\n\x0b\x63ustom_dims\x18\x05 \x03(\x0b\x32%.com.vectara.indexing.CustomDimension\x12.\n\x07section\x18\n \x03(\x0b\x32\x1d.com.vectara.indexing.Section\"\xc6\x01\n\x08\x44ocument\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rmetadata_json\x18\x04 \x01(\t\x12:\n\x0b\x63ustom_dims\x18\x05 \x03(\x0b\x32%.com.vectara.indexing.CustomDimension\x12.\n\x07section\x18\n \x03(\x0b\x32\x1d.com.vectara.indexing.SectionBI\n\x14\x63om.vectara.indexingB\x0eIndexingProtosZ!vectara.com/public/proto/indexingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indexing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.vectara.indexingB\016IndexingProtosZ!vectara.com/public/proto/indexing'
  _SECTION._serialized_start=59
  _SECTION._serialized_end=240
  _DOCUMENT._serialized_start=243
  _DOCUMENT._serialized_end=441
# @@protoc_insertion_point(module_scope)
