# Generated by Django 4.1.5 on 2023-01-24 23:10

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="google_client_id",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="google_client_secret",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="google_refresh_token",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="google_scopes",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="google_token",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
    ]
