# Generated by Django 4.1.5 on 2023-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_workspace_google_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="google_active",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
