# Generated by Django 4.1.5 on 2023-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_workspace_google_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="identifier",
            field=models.CharField(db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document", name="title", field=models.TextField(blank=True),
        ),
    ]
