# Generated by Django 4.1.5 on 2023-01-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_document_identifier_document_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document", old_name="word_count", new_name="size",
        ),
    ]
