# Generated by Django 4.1.5 on 2023-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_word_count_document_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="section", name="link",),
        migrations.AddField(
            model_name="section",
            name="section_id",
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
