# Generated by Django 4.1.5 on 2023-01-27 12:11

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_section_link_section_section_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="corpus_id",
            field=fernet_fields.fields.EncryptedIntegerField(default=None, null=True),
        ),
    ]
