# Generated by Django 4.1.5 on 2023-01-28 00:02

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_workspace_corpus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="text",
            field=fernet_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
