# Generated by Django 4.1.6 on 2023-02-06 17:14

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_section_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="slack_active",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="slack_client_id",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="slack_client_secret",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="slack_refresh_token",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="slack_scopes",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="slack_token",
            field=fernet_fields.fields.EncryptedTextField(default=None, null=True),
        ),
    ]
