# Generated by Django 4.1.6 on 2023-02-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_workspace_slack_active_workspace_slack_client_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(db_index=True, max_length=255)),
                ("slack_workspace_name", models.CharField(max_length=255)),
                ("channel_name", models.CharField(max_length=255)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
    ]
