# Generated by Django 4.1.6 on 2023-02-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_slackbot_slackinstallation_slackoauthstate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="workspace", name="slack_client_id",),
        migrations.RemoveField(model_name="workspace", name="slack_client_secret",),
        migrations.RemoveField(model_name="workspace", name="slack_refresh_token",),
        migrations.RemoveField(model_name="workspace", name="slack_scopes",),
        migrations.RemoveField(model_name="workspace", name="slack_token",),
        migrations.AddField(
            model_name="slackchannel",
            name="slack_workspace_id",
            field=models.CharField(db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspace",
            name="slack_workspace_id",
            field=models.CharField(
                db_index=True, default=None, max_length=255, null=True
            ),
        ),
    ]
